### ISSUE TITLE
OCI Feedback & Optimisations

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/python-gardenlinux-cli#16]
- [x] stop extracting tarballs gardenlinux/python-gardenlinux-lib#75 
- [x] parallel push, refactor & cleanup gardenlinux/python-gardenlinux-cli#20 
- [x] add description field gardenlinux/python-gardenlinux-cli#18
